/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author intel
 */
public class Frame1 extends javax.swing.JFrame {

    String jns="";
    int jml;
    
    public Frame1() {
        initComponents();
        jns=null;
        Panel1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jenis = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        Panel1 = new javax.swing.JPanel();
        bila1 = new javax.swing.JLabel();
        bil1 = new javax.swing.JTextField();
        bila2 = new javax.swing.JLabel();
        bil2 = new javax.swing.JTextField();
        bila3 = new javax.swing.JLabel();
        bil3 = new javax.swing.JTextField();
        bila4 = new javax.swing.JLabel();
        bil4 = new javax.swing.JTextField();
        hitung = new javax.swing.JButton();
        hasil = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jumlah = new javax.swing.JComboBox<>();
        keterangan = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tekton Pro", 3, 24)); // NOI18N
        jLabel4.setText("PROGRAM   ARITMATIKA");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(100, 30, 250, 30);

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabel2.setText("Jenis Aritmatika");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 80, 130, 20);

        jenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "~~~ Pilih Salah Satu ~~~", "Penjumlahan", "Pengurangan", "Perkalian", "Pembagian" }));
        jenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisActionPerformed(evt);
            }
        });
        getContentPane().add(jenis);
        jenis.setBounds(210, 80, 170, 20);

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));
        jPanel1.setLayout(null);

        Panel1.setBackground(new java.awt.Color(102, 204, 255));
        Panel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Operasi"));
        Panel1.setLayout(null);

        bila1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        bila1.setText("Bilangan 1");
        Panel1.add(bila1);
        bila1.setBounds(23, 96, 90, 20);
        Panel1.add(bil1);
        bil1.setBounds(189, 96, 170, 20);

        bila2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        bila2.setText("Bilangan 2");
        Panel1.add(bila2);
        bila2.setBounds(23, 134, 100, 20);
        Panel1.add(bil2);
        bil2.setBounds(189, 134, 170, 20);

        bila3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        bila3.setText("Bilangan 3");
        Panel1.add(bila3);
        bila3.setBounds(23, 172, 90, 20);
        Panel1.add(bil3);
        bil3.setBounds(189, 172, 170, 20);

        bila4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        bila4.setText("Bilangan 4");
        Panel1.add(bila4);
        bila4.setBounds(23, 203, 90, 20);
        Panel1.add(bil4);
        bil4.setBounds(189, 203, 170, 20);

        hitung.setText("HITUNG");
        hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungActionPerformed(evt);
            }
        });
        Panel1.add(hitung);
        hitung.setBounds(189, 234, 100, 30);
        Panel1.add(hasil);
        hasil.setBounds(189, 270, 143, 50);

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabel3.setText("Jumlah Bilangan");
        Panel1.add(jLabel3);
        jLabel3.setBounds(23, 55, 130, 30);

        jumlah.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4" }));
        jumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahActionPerformed(evt);
            }
        });
        Panel1.add(jumlah);
        jumlah.setBounds(189, 55, 170, 30);

        keterangan.setFont(new java.awt.Font("Tekton Pro Cond", 1, 18)); // NOI18N
        Panel1.add(keterangan);
        keterangan.setBounds(109, 16, 148, 28);

        jPanel1.add(Panel1);
        Panel1.setBounds(32, 128, 440, 380);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-10, 0, 510, 550);

        setBounds(0, 0, 498, 567);
    }// </editor-fold>//GEN-END:initComponents

    private void jenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisActionPerformed
        // TODO add your handling code here:
        
        setjenis();
    }//GEN-LAST:event_jenisActionPerformed

    private void hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungActionPerformed
        // TODO add your handling code here:
        
        Double hsl=0.0;
        Double a1,a2,a3,a4;
        a1=Double.parseDouble(bil1.getText().toString());
        a2=Double.parseDouble(bil2.getText().toString());
        
        if(jns.equals("Penjumlahan"))
        {
            if(jml==2)
            {
                hsl=a1+a2;
                hasil.setText(""+a1 + "+"+ a2 +" = "+hsl);
            }
            if(jml==3)
            {
                a3=Double.parseDouble(bil3.getText().toString());
                hsl=a1+a2+a3;
                hasil.setText(""+ a1 + "+" + a2 + "+" + a3 +"="+hsl);
            }
            if(jml==4)
            {
                a3=Double.parseDouble(bil3.getText().toString());
                a4=Double.parseDouble(bil4.getText().toString());
                hsl=a1+a2+a3+a4;
                hasil.setText(""+a1 + "+"+ a2 +"+"+a3 + "+"+ a4 +" = "+hsl);
            }
        }
        else if(jns.equals("Pengurangan"))
        {
            if(jml==2)
            {
                hsl=a1-a2;
                hasil.setText(""+a1 + "-"+ a2 +" = "+hsl);
            }
            if(jml==3)
            {
                a3=Double.parseDouble(bil3.getText().toString());
                hsl=a1-a2-a3;
                hasil.setText(""+ a1 + "-" + a2 + "-" + a3 +"="+hsl);
            }
            if(jml==4)
            {
                a3=Double.parseDouble(bil3.getText().toString());
                a4=Double.parseDouble(bil4.getText().toString());
                hsl=a1-a2-a3-a4;
                hasil.setText(""+a1 + "-"+ a2 +"-"+a3 + "-"+ a4 +" = "+hsl);
            }
        }
        else if(jns.equals("Perkalian"))
        {
            if(jml==2)
            {
                hsl=a1*a2;
                hasil.setText(""+a1 + "x"+ a2 +" = "+hsl);
            }
            if(jml==3)
            {
                a3=Double.parseDouble(bil3.getText().toString());
                hsl=a1*a2*a3;
                hasil.setText(""+ a1 + "x" + a2 + "x" + a3 +"="+hsl);
            }
            if(jml==4)
            {
                a3=Double.parseDouble(bil3.getText().toString());
                a4=Double.parseDouble(bil4.getText().toString());
                hsl=a1*a2*a3*a4;
                hasil.setText(""+a1 + "x"+ a2 +"x"+a3 + "x"+ a4 +" = "+hsl);
            }
        }
        else if(jns.equals("Pembagian"))
        {
            if(jml==2)
            {
                hsl=a1/a2;
                hasil.setText(""+a1 + ":"+ a2 +" = "+hsl);
            }
            if(jml==3)
            {
                a3=Double.parseDouble(bil3.getText().toString());
                hsl=a1/a2/a3;
                hasil.setText(""+ a1 + ":" + a2 + ":" + a3 +"="+hsl);
            }
            if(jml==4)
            {
                a3=Double.parseDouble(bil3.getText().toString());
                a4=Double.parseDouble(bil4.getText().toString());
                hsl=a1-a2/a3/a4;
                hasil.setText(""+a1 + ":"+ a2 +":"+a3 + ":"+ a4 +" = "+hsl);
            }
        }
    }//GEN-LAST:event_hitungActionPerformed

    private void jumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahActionPerformed
        // TODO add your handling code here:
        getJumlah();
    }//GEN-LAST:event_jumlahActionPerformed
      public void setjenis()
    {
        if(jenis.getSelectedItem().equals("Penjumlahan"))
        {
            jns="Penjumlahan";
            keterangan.setText("Penjumlahan");
           Panel1.setVisible(true);
            jumlah.setEnabled(true);
        }
        else if(jenis.getSelectedItem().equals("Pengurangan"))
        {
            jns="Pengurangan";
            keterangan.setText("Pengurangan");
            Panel1.setVisible(true);
            jumlah.setEnabled(true);
        }
         else if(jenis.getSelectedItem().equals("Perkalian"))
        {
            jns="Perkalian";
            keterangan.setText("Perkalian");
            Panel1.setVisible(true);
            jumlah.setEnabled(true);
        }
         else if(jenis.getSelectedItem().equals("Pembagian"))
        {
            jns="Pembagian";
            keterangan.setText("Pembagian");
            Panel1.setVisible(true);
            jumlah.setEnabled(true);
        }
         else {
             jns=null;
             Panel1.setVisible(false);
         }
    }
    public void getJumlah()
    {
        if(jumlah.getSelectedItem().equals("2"))
        {
            bila3.setVisible(false);
            bila4.setVisible(false);
            bil3.setVisible(false);
            bil4.setVisible(false);
            jml = 2;
        }
        else if(jumlah.getSelectedItem().equals("3"))
        {
            bila3.setVisible(true);
            bila4.setVisible(false);
            bil3.setVisible(true);
            bil4.setVisible(false);
            jml = 3;
        }
        else if(jumlah.getSelectedItem().equals("4"))
        {
            bila3.setVisible(true);
            bila4.setVisible(true);
            bil3.setVisible(true);
            bil4.setVisible(true);
            jml = 4;
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel1;
    private javax.swing.JTextField bil1;
    private javax.swing.JTextField bil2;
    private javax.swing.JTextField bil3;
    private javax.swing.JTextField bil4;
    private javax.swing.JLabel bila1;
    private javax.swing.JLabel bila2;
    private javax.swing.JLabel bila3;
    private javax.swing.JLabel bila4;
    private javax.swing.JTextField hasil;
    private javax.swing.JButton hitung;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jenis;
    private javax.swing.JComboBox<String> jumlah;
    private javax.swing.JLabel keterangan;
    // End of variables declaration//GEN-END:variables
}
